src/routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\ProfileController;
use App\Service\OpenAIService;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomePage::class)->name('home');
Route::get('/dashboard', DashBoard::class)->name('dashboard');
/*
Route::get('/dashboard', function ($missatge = 'Benvingut al teu perfil') {
    return view('dashboard')->with('missatge', $missatge);
})->middleware(['auth', 'verified'])->name('dashboard');
*/

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware('is_admin')->group(function () {
    Route::Resource('users', UserController::class);
});

require __DIR__.'/auth.php';

// Rutes per a llibres
Route::Resource('books', BookController::class);
Route::get('/books/{book}/admetre', [BookController::class, 'admetre'])->name('books.admetre');
Route::post('/books/{book}/sale', [BookController::class, 'sale'])->name('books.sale')->middleware('auth');

// Rutes per a cursos
Route::Resource('courses', CourseController::class);

// Rutes per a famílies
Route::Resource('families', FamilyController::class);

// Rutes per a mòduls
Route::Resource('modules', ModuleController::class);
// Rutes per a vendes
Route::Resource('sales', SaleController::class);

// Rutes per a openai
Route::get('/openai', [OpenAIService::class, 'index'])->name('openai.index');
Route::get('/chat', [ChatController::class, 'index']);
Route::post('/chat/send', [ChatController::class, 'sendMessage']);
// Rutes per a google

Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');

src/app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $fillable = [
        'photo',
        'module_id',
        'price',
        'pages',
        'user_id',
        'publisher',
        'comments',
        'status'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function module()
    {
        return $this->belongsTo(Module::class, 'module_id', 'code');
    }

    public function sales()
    {
        return $this->hasMany(Sale::class);
    }
}

src/app/Http/Controllers/Api/BookController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\BookRequest;
use App\Http\Resources\BookCollection;
use App\Http\Resources\BookResource;
use App\Models\Book;
use App\Notifications\BookNewNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $books = Book::paginate(10);
        return new BookCollection($books);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(BookRequest $request)
    {
        $validatedData = $request->toArray();

        if ($request->hasFile('photo')) {
            $path = $request->file('photo')->store('public/books');
            $validatedData['photo'] = Storage::url($path);
        }
        $validatedData['user_id'] = Auth::user()->id;

        $book = Book::create($validatedData);
        administrador()->notify(new BookNewNotification($book));

        return response()->json(new BookResource($book),200);
    }

    /**
     * Display the specified resource.
     */
    public function show(Book $book)
    {
        return response()->json(new BookResource($book),200);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Book $book)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Book $book)
    {
        //
    }
}

src/app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BookRequest;
use App\Http\Services\AlertService;
use App\Http\Services\ChatGTPService;
use App\Mail\PurchaseConfirmationMail;
use App\Models\Book;
use App\Models\Sale;
use App\Notifications\BookNewNotification;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    // Mostra la llista de llibres
    public function index()
    {
        $books = Auth::user()->administrador? Book::paginate(20) : Book::where('user_id', Auth::user()->id)->paginate(20);
        return view('books.index', compact('books'));
    }

    // Mostra el formulari per a crear un nou llibre
    public function create()
    {
        return view('books.create');
    }

    // Emmagatzema un nou llibre
    public function store(BookRequest $request)
    {
        $validatedData = $request->toArray();

        if ($request->hasFile('photo')) {
            $path = $request->file('photo')->store('public/books');
            $validatedData['photo'] = Storage::url($path);
        }
        $validatedData['user_id'] = Auth::user()->id;

        $book = Book::create($validatedData);
        administrador()->notify(new BookNewNotification($book));
        AlertService::info('Llibre creat correctament');


        // Redirigeix o retorna una resposta segons siga necessari
        return redirect()->route('books.show', $book->id);
    }

    public function admetre(Book $book)
    {
        $book->admes = true;
        $book->save();
        return redirect()->route('books.show', $book->id);
    }

    public function sale(Book $book)
    {
        $book->soldDate = now()->format('Y-m-d');
        $book->save();
        $sale = new Sale([
            'book_id' => $book->id,
            'user_id' => Auth::user()->id,
            'date' => $book->soldDate,
            'status' => 1
        ]);
        $sale->save();
        $venedor = $book->User;
        Mail::to($venedor->email)->send(new PurchaseConfirmationMail($sale));

        return redirect()->route('books.show', $book->id);
    }

    // Mostra un llibre específic
    public function show(Book $book)
    {
        $response = new ChatGTPService();
        $reply = $response->response("Fes un index d'un llibre de Formació Professional amb títol: ".
            $book->Module->vliteral);
        $message = '';
        foreach ($reply as $r){
            if ($r['message']['role'] == 'assistant') {
                $message .= $r['message']['content'];
            }
        }
        return view('books.show', compact('book','message'));
    }

    // Mostra el formulari d'edició per a un llibre específic
    public function edit(Book $book)
    {
        return view('books.edit', compact('book'));
    }

    // Actualitza un llibre específic
    public function update(BookRequest $request, Book $book)
    {
        $validatedData = $request->toArray();

        if ($request->hasFile('photo')) {
            $path = $request->file('photo')->store('public/books');
            $validatedData['photo'] = Storage::url($path);
        }

        // Redirigeix o retorna una resposta segons siga necessari
        $book->update($validatedData);
        AlertService::info('Llibre actualitzat correctament');
        return redirect()->route('books.show', $book->id);

    }

    // Elimina un llibre específic
    public function destroy(Book $book)
    {
        $book->delete();
        AlertService::warning('Llibre eliminat correctament');
        return redirect()->route('books.index');
    }
}

src/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

src/resources/views/books/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Alta Llibre') }}
        </h2>
    </x-slot>
    <div class="container mx-auto px-4">
        <h1 class="text-xl font-bold mb-4">Crear Llibre</h1>
        <!-- Mostrar Errors de Validació -->
        @include('partials.validation-errors')
        <form action="{{ route('books.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="mb-4">
                <label for="module_id" class="block text-gray-700 text-sm font-bold mb-2">Mòdul ID:</label>
                <select name="module_id" id="module_id" class="shadow border rounded w-full py-2 px-3 text-gray-700">
                    @foreach (\App\Models\Module::all() as $module)
                        <option value="{{ $module->code }}" {{ old('module_id') == $module->code ? 'selected' : '' }}>{{ $module->vliteral }}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-4">
                <label for="publisher" class="block text-gray-700 text-sm font-bold mb-2">Editorial:</label>
                <input type="text" name="publisher" id="publisher" value="{{ old('publisher') }}" class="shadow border rounded w-full py-2 px-3 text-gray-700">
            </div>

            <div class="mb-4">
                <label for="price" class="block text-gray-700 text-sm font-bold mb-2">Preu:</label>
                <input type="number" name="price" id="price" value="{{ old('price') }}" class="shadow border rounded w-full py-2 px-3 text-gray-700">
            </div>

            <div class="mb-4">
                <label for="pages" class="block text-gray-700 text-sm font-bold mb-2">Pàgines:</label>
                <input type="number" name="pages" id="pages" value="{{ old('pages') }}" class="shadow border rounded w-full py-2 px-3 text-gray-700">
            </div>

            <div class="mb-4">
                <label for="status" class="block text-gray-700 text-sm font-bold mb-2">Estat:</label>
                <select name="status" id="status" class="shadow border rounded w-full py-2 px-3 text-gray-700">
                    <option value="new" {{ old('status') == 'new' ? 'selected' : '' }}>Nou</option>
                    <option value="good" {{ old('status') == 'good' ? 'selected' : '' }}>Bo</option>
                    <option value="used" {{ old('status') == 'used' ? 'selected' : '' }}>Usat</option>
                    <option value="bad" {{ old('status') == 'bad' ? 'selected' : '' }}>Dolent</option>
                </select>
            </div>

            <div class="mb-4">
                <label for="photo" class="block text-gray-700 text-sm font-bold mb-2">Foto:</label>
                <input type="file" name="photo" id="photo" class="shadow border rounded w-full py-2 px-3 text-gray-700">
            </div>

            <div class="mb-4">
                <label for="comments" class="block text-gray-700 text-sm font-bold mb-2">Comentaris:</label>
                <textarea name="comments" id="comments" rows="3" class="shadow border rounded w-full py-2 px-3 text-gray-700">
                    {{ old('comments') }}
                </textarea>
            </div>
            <button type="submit" class="bg-green-700 hover:bg-blue-700 font-bold py-2 px-4 rounded">
                Guardar Llibre
            </button>
        </form>
    </div>
</x-app-layout>

src/resources/views/books/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Editar Llibre') }}
        </h2>
    </x-slot>
    <div class="container mx-auto px-4">
        <h1 class="text-xl font-bold mb-4">Editar Llibre</h1>
        <!-- Mostrar Errors de Validació -->
        @include('partials.validation-errors')
        <form action="{{ route('books.update', $book->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="mb-4">
                <label for="module_id" class="block text-gray-700 text-sm font-bold mb-2">Mòdul ID:</label>
                <select name="module_id" id="module_id" class="shadow border rounded w-full py-2 px-3 text-gray-700">
                    @foreach (\App\Models\Module::all() as $module)
                        <option value="{{ $module->code }}"
                            {{ old('module_id', $book->module_id) == $module->code ? 'selected' : '' }}>
                            {{ $module->vliteral }}
                        </option>
                    @endforeach
                </select>
            </div>

            <!-- Resta de camps amb valors existents del llibre -->
            <div class="mb-4">
                <label for="publisher" class="block text-gray-700 text-sm font-bold mb-2">Editorial:</label>
                <input type="text" name="publisher" id="publisher"
                       value="{{ old('publisher', $book->publisher) }}"
                       class="shadow border rounded w-full py-2 px-3 text-gray-700"
                >
            </div>

            <div class="mb-4">
                <label for="price" class="block text-gray-700 text-sm font-bold mb-2">Preu:</label>
                <input type="number" name="price" id="price"
                       value="{{old('price',$book->price) }}"
                       class="shadow border rounded w-full py-2 px-3 text-gray-700"
                >
            </div>

            <div class="mb-4">
                <label for="pages" class="block text-gray-700 text-sm font-bold mb-2">Pàgines:</label>
                <input type="number" name="pages" id="pages"
                       value="{{ old('pages', $book->pages) }}"
                       class="shadow border rounded w-full py-2 px-3 text-gray-700"
                >
            </div>

            <div class="mb-4">
                <label for="status" class="block text-gray-700 text-sm font-bold mb-2">Estat:</label>
                <select name="status" id="status" class="shadow border rounded w-full py-2 px-3 text-gray-700">
                    <option value="new" {{ old('status', $book->status) == 'new' ? 'selected' : '' }}>Nou</option>
                    <option value="good" {{ old('status', $book->status) == 'good' ? 'selected' : '' }}>Bo</option>
                    <option value="used" {{ old('status', $book->status) == 'used' ? 'selected' : '' }}>Usat</option>
                    <option value="bad" {{ old('status', $book->status) == 'bad' ? 'selected' : '' }}>Dolent</option>
                </select>
            </div>

            <div class="mb-4">
                <label for="photo" class="block text-gray-700 text-sm font-bold mb-2">Foto:</label>
                <input type="file" name="photo" id="photo" class="shadow border rounded w-full py-2 px-3 text-gray-700">
            </div>

            <div class="mb-4">
                <label for="comments" class="block text-gray-700 text-sm font-bold mb-2">Comentaris:</label>
                <textarea name="comments" id="comments" rows="3" class="shadow border rounded w-full py-2 px-3 text-gray-700">
                    {{old('comments', $book->comments)}}
                </textarea>
            </div>

            <button type="submit" class="bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded">
                Actualitzar Llibre
            </button>
        </form>
    </div>
</x-app-layout>

src/resources/views/books/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Llibres') }}
        </h2>
    </x-slot>
    <div class="container mx-auto px-4">
        <table class="table-auto w-full mt-4">
            <thead>
            <tr class="bg-gray-100">
                <th class="px-4 py-2">Mòdul</th>
                <th class="px-4 py-2">Cicle</th>
                <th class="px-4 py-2">Editorial</th>
                <th class="px-4 py-2">Preu</th>
                <!-- Altres capsaleres de taula -->
                <th class="px-4 py-2">Accions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($books as $book)
                <tr>
                    <td class="border px-4 py-2">{{ $book->Module->vliteral }}</td>
                    <td class="border px-4 py-2">{{ $book->Module->Course->vliteral }}</td>
                    <td class="border px-4 py-2">{{ $book->publisher }}</td>
                    <td class="border px-4 py-2">{{ $book->price }}</td>
                    <!-- Altres camps de llibre -->
                    <td class="border px-4 py-2">
                        <a href="{{ route('books.show', $book) }}" class="text-blue-600 hover:text-blue-900">Veure</a>
                        <a href="{{ route('books.edit', $book) }}" class="text-green-600 hover:text-green-900">Editar</a>
                        <form action="{{ route('books.destroy', $book) }}" method="POST" class="inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="text-red-600 hover:text-red-900">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $books->links() }}
    </div>
</x-app-layout>

src/resources/views/books/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Mostrar Llibre') }}
        </h2>
    </x-slot>
    <div class="container mx-auto px-4">
        <div class="mb-4">
            <x-book-card book="{{$book->id}}" />
            <p>{{$message}}</p>
        </div>
    </div>
</x-app-layout>